### PR TITLE
Update/usability test

### PR DESCRIPTION
**Pull request by emily-costa**
@kvlinden I have applied your feedback to our test script. If you could please look over it to make sure I didn't miss anything I'd greatly appreciate it. Thank you!

### CODE REVIEW

**Comment by kvlinden** [comment]
Comments:

- Task 1 - Drop that last question (information entering); you'll be able to see that from their behavior.
- Tasks 2.1 & 2.3 - I'd put these login tasks inside the "say you are a X" super-tasks.
- Task 2.4.1 - Just say "The desk has just received a large white envelop for Emily Costa (eac2). Can you add this to the system?" Using the words navigate and screen telegraphs information. And I don't get how the two sub-tasks (4.1.1 & 4.1.2) go together. Either have the manually enter a second package or just have them enter one in any way they'd like.
- Task 2.4.2 - Just say "You want to look at the packages that still need to be picked up by EAC2. Can you do this?"
- Tasks 2.4.3 & 2.4.4 - Make the same changes here.
- Task 3 - Don't ask if it will be "easy to use"; you'll be able to tell that from their behavior. If they don't think they'll use the app, it would be worth asking why.

I'm happy to read another draft on this.

**Comment by emily-costa** [comment]
@kvlinden Here is the new draft. If you could please review it I'd appreciate it. Thank you!

**Comment by kvlinden** [comment]
That looks solid. The only thing I notice now is the asymmetry between the 1.x tasks, which all end in an imperative (e.g., "Find this information.") and the 2.x tasks, which all end in a question (e.g., "Can you add this to the system?"). I'd change the latter to imperatives (e.g., "Add this [new package] to the system.").

**Comment by emily-costa** [comment]
@colemanulry I have updated the script with all of VanderLinden's edits... can you please review and merge it

**Comment by colemanulry** [comment]
Looks good, thanks!

**Pull request merged**
